name: build .deb package

on:
  push:
    branches: [ "master", "ci-cd-setup" ]

jobs:
  build-deb:
    name: builds a debian package
    runs-on: ubuntu-22.04

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install build deps
        run: |
             sudo apt update
             sudo apt install -y build-essential debhelper devscripts fakeroot cmake qtbase5-dev

      - name: build the package
        id: build-deb
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: -us -uc -b
          extra-build-deps: build-essential debhelper devscripts fakeroot cmake qtbase5-dev

      - name: post artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dirview-assignment-artifacts
          path: ${{ steps.build-deb.outputs.artifacts }}
          retention-days: 30
 
